{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"private_outputs":true,"provenance":[],"authorship_tag":"ABX9TyMGhq1Lcks9wHwqCr/QLK7R"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["# Excepciones en Python\n","## Manejo de errores"],"metadata":{"id":"5M6fA77_hUZm"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"BtXSaR5PhOOl"},"outputs":[],"source":["numerador = int(input('Ingrese el numerador: '))\n","denominador = int(input('Ingrese el denominador (distinto de CERO): '))\n","\n","try :\n","  cociente = numerador / denominador\n","  print(nombre)\n","\n","except NameError:\n","  print('Tenemos problemas con algun nombre')\n","\n","except ZeroDivisionError:\n","  print('Tenemos problemas con algun denominador en CERO')\n","\n","else:\n","  print('El cociente es igual a', cociente)\n","\n","finally:\n","  print('Ya tengo las excepciones bajo control')\n"]}]}